db;

db.insert({
	name: "",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});

db.insert({
	name: "Cosmea Ammerschläger",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Hannah-Sofie Arens",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Abdul Samet Baser",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Christian Bettermann",
	englisch5: "4",
	mathe: "3",
	physik: "3",
	deutsch: "3",
	geschichte: "1",
	kunst: "2",
	sozialwissenschaften: "3",
	erdkunde: "1",
	chemie: "2",
	informatik: "2",
	kreligion: "3",
	sport: "4"
});
db.insert({
	name: "Florian Biedermann",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Maximilian Busch",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Jasmin Drilling",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Luis Leonard Duhme",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Viktoria Goeke",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Pia Gronemann",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Annika Hohmann",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Maren Hohmann",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Felix Joshua Hölter",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Linus Milan Tobias Hommel",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Juliane Kaiser",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Pia Josefine Kröger",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Jendrik Mölle",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Marta Paic",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Joana Pirzkall",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Julia Puchalla",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Nele Riesenberg",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Senja Maren Ritzmann",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Nora Schieferdecker",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Lara Franziska Schmitz",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Anna Sinn",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	ereligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Julien Wache",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Paulina Walden",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Zoe Westheide",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Marcel Wette",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});
db.insert({
	name: "Melina Zikou",
	deutsch: "",
	englisch5: "",
	latein6: "",
	latein8: "",
	französisch6: "",
	französisch8: "",
	spanisch: "",
	kunst: "",
	musik: "",
	geschichte: "",
	sozialwissenschaften: "",
	erdkunde: "",
	paedagogik: "",
	philosophie: "",
	biologie: "",
	chemie: "",
	physik: "",
	informatik: "",
	mathe: "",
	kreligion: "",
	englischvertierfung: "",
	mathematikvertierfung: ""
});